import os

WATSON_ASSISTANT_API_KEY = os.getenv('WATSON_ASSISTANT_API_KEY')
WATSON_ASSISTANT_URL = os.getenv('WATSON_ASSISTANT_URL')
WATSON_NLU_API_KEY = os.getenv('WATSON_NLU_API_KEY')
WATSON_NLU_URL = os.getenv('WATSON_NLU_URL')
WATSON_TONE_ANALYZER_API_KEY = os.getenv('WATSON_TONE_ANALYZER_API_KEY')
WATSON_TONE_ANALYZER_URL = os.getenv('WATSON_TONE_ANALYZER_URL')
WATSON_DISCOVERY_API_KEY = os.getenv('WATSON_DISCOVERY_API_KEY')
WATSON_DISCOVERY_URL = os.getenv('WATSON_DISCOVERY_URL')
